name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Start SonarCloud analysis
        run: >
          dotnet sonarscanner begin
          /k:"Mikado1405_Electron.NET"
          /o:"my-organization-sonar-cloud"
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          /d:sonar.host.url="https://sonarcloud.io"

      - name: Build Solution
        working-directory: src
        run: |
          sln_file=$(find . -maxdepth 1 -name "*.sln" | head -n 1)
          echo "Detected solution file: $sln_file"
          dotnet build "$sln_file"

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
